Feat/add di
kysect/BotFramework pull request #23
Opened 2021-04-19 20:35 UTC by FrediKats

С большой вероятностью, для реализации логики команд нужно будет протягивать другие типы - зависимости от дб, сервисов. Все сойдется к тому, что команда - это контроллер от мира бот фреймворка. Хорошим решением в таком случае будет добавить поддержку DI, чтобы команды резолвились и создавались через него. Отдельным бонусом будет то, что инстансы будут создаваться независимо на каждый вызов, а не 1 экземпляр команды, который шарится на все приложение на каждый вызов.

2021-04-19 21:53 UTC, Bibletoon requested changes

2021-04-19 21:53 UTC, Bibletoon commented on Kysect.BotFramework/Commands/PingCommand.cs
> +            new string[0]);
Лучше сделать конструктор с двумя параметрами

2021-04-19 21:53 UTC, Bibletoon commented on Kysect.BotFramework/Core/CommandInvoking/CommandHolder.cs
> +                if (_caseSensitive && string.Equals(command.CommandName, commandName, StringComparison.InvariantCultureIgnoreCase))
Должно быть !_caseSensetive

2021-04-19 21:53 UTC, Bibletoon commented on Kysect.BotFramework.ConsoleTest/Program.cs
> +                .AddCommand(PingCommand.Descriptor)
Команда не регистрируется в ServiceCollection

2021-04-20 18:25 UTC, annchous commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +        public  ServiceCollection ServiceCollection { get; } = new ServiceCollection();
Да, я душнила, но тут лишний пробел после `public`.

2021-04-20 21:14 UTC, Bibletoon approved these changes

2021-04-20 21:30 UTC, s4xack requested changes

2021-04-20 21:30 UTC, s4xack commented on Kysect.BotFramework/Core/CommandInvoking/CommandHandler.cs
> +
лишния пустая строка

2021-04-20 21:30 UTC, s4xack commented on Kysect.BotFramework/Core/CommandInvoking/CommandHandler.cs
>                  }
можно бы и в свич развернуть

2021-04-20 21:41 UTC, merged