Feat/upgrade media system
kysect/BotFramework pull request #25
Opened 2021-05-05 07:42 UTC by Bibletoon

2021-05-05 08:46 UTC, FrediKats requested changes
Немного сложноватый код получился, очень много ветвлений.

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +        private MediaTypeEnum parseMediaType(string filename)
Кодстайл

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    botMessage = new BotTextMessage(context.Message.Content);
А если нет поддерживаемых медиа и нет текста?

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            if (filename.EndsWith("png") || filename.EndsWith("jpg") ||
Можно через FileInfo достать экстеншен, чтобы хендлить ситуации когда тебе кидают файл без экстеншена у которого просто конец названия совпадает. Не уверен, что это законно, но да ладно.

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                botMessage = parseMediaType(message.Attachments.First().Filename) switch
Нужно залогировать какие типы приложенных файлов не были обработаны.

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                    message = new BotTextMessage(text);
Тут же тоже текста может не быть, да?

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                if (!mediaFiles.Any())
Не очень нравится, что у тебя сначала один if/elif/else, а потом еще раз такой же.

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    botMessage = new BotSingleMediaMessage(context.Message.Content, mediaFiles.First());
А сообщение с одним медиа не являются подможеством сообщений с N медиа?

2021-05-05 08:46 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                    message = new BotSingleMediaMessage(text, mediaFile);
Я бы свитчи, которые что-то возвращают и все - выносил бы в методы, чтобы там вместо брейков return'ы были.

2021-05-05 08:52 UTC, VitalDikov commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                }
Какая то очень странная конструкция. ПОчему обработка первого элемента идёт отдельно? Если это прям необходимо, может выделить в отдельный метод?

2021-05-05 08:54 UTC, VitalDikov commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            if (result.IsFailed) return result;
мне кажется этот иф можно инвертировать. так как метод в любом случае вернет резалт. if(!result.IsFailed) result = SendText(file.Path, sender);

2021-05-05 08:55 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    botMessage = new BotTextMessage(context.Message.Content);
То дальше пойдёт сообщение с пустым текстом, которое отпадёт на этапе обработки имени команды

2021-05-05 08:57 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    botMessage = new BotSingleMediaMessage(context.Message.Content, mediaFiles.First());
Нет, в Телеграмме если медиа больше одного, они отправляются по другому

2021-05-05 08:58 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                }
Потому что клоунский дискорд не умеет в отправку группы медиа, и что бы не потерять текст его нужно отправлять вместе с первым файлом.

Насчёт метода подумаю

2021-05-05 08:59 UTC, VitalDikov commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            }
слишком много if else, читать проблематично. Ты уверен что это всё нельзя разделить? Как минимум кейсы context.Message.Attachments.Count == 0, if context.Message.Attachments.Count == 1 и if context.Message.Attachments.Count > 1 можно выделить в отдельные блоки

2021-05-05 09:01 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            if (result.IsFailed) return result;
Звучит валидно, но мне как-то эстетически не нравится внешний вид варианта с инвертированным ифом.

2021-05-05 09:01 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +        private MediaTypeEnum parseMediaType(string filename)
Fixed

2021-05-05 09:03 UTC, VitalDikov commented on Kysect.BotFramework/Commands/PingCommand.cs
> +            IBotMessage message = new BotSingleMediaMessage("Hi!", new BotOnlinePhotoFile("https://www.ferra.ru/thumb/1800x0/filters:quality(75):no_upscale()/imgs/2020/12/09/06/4390537/dd4dfcc4320bfd
Вхардкоженно. Хотя бы заведи переменную

2021-05-05 09:21 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                filename.EndsWith("wmv") || filename.EndsWith("avi")) return MediaTypeEnum.Video;
хайпово

2021-05-05 09:23 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +            }
Сильно, можно же просто 2 аргумент заифать и не копипастить свитчи
А вообще я уже миллион свитчей на тип видел, там нельзя как-то на дженериках красиво выхеать?

2021-05-05 09:24 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                task.Wait();
Записал тебя карандашом в список

2021-05-05 09:25 UTC, hrrrrustic commented on Kysect.BotFramework/Core/BotMedia/BotPhotoFile.cs
> +    public class BotPhotoFile : IBotMediaFile
респект

2021-05-05 09:26 UTC, hrrrrustic commented on Kysect.BotFramework/Core/BotMedia/IBotOnlineFile.cs
> +        public string Id { get; }
~~public~~

2021-05-05 12:27 UTC, annchous commented on Kysect.BotFramework/Core/BotMedia/BotPhotoFile.cs
> +    public class BotPhotoFile : IBotMediaFile
+

2021-05-05 12:28 UTC, annchous commented on Kysect.BotFramework/Core/BotMedia/IBotOnlineFile.cs
> +        public string Id { get; }
> ~public~

```suggestion
        string Id { get; }
```

2021-05-05 12:33 UTC, hrrrrustic commented on Kysect.BotFramework/Core/BotMedia/IBotOnlineFile.cs
> +        public string Id { get; }
```suggestion
        string Id { get; }
```

Ну тоже так умею и чо

2021-05-05 12:38 UTC, VitalDikov commented on Kysect.BotFramework/Core/BotMedia/BotPhotoFile.cs
> +    public class BotPhotoFile : IBotMediaFile
по факту

2021-05-05 12:41 UTC, annchous commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendOnlineMedia(IBotOnlineFile file, string text, SenderInfo sender);
```suggestion
        Result<string> SendMedia(IBotMediaFile mediaFile, string text, SenderInfo sender);
        Result<string> SendMultipleMedia(List<IBotMediaFile> mediaFiles, string text, SenderInfo sender);
        Result<string> SendOnlineMedia(IBotOnlineFile file, string text, SenderInfo sender);
```

2021-05-05 13:04 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendOnlineMedia(IBotOnlineFile file, string text, SenderInfo sender);
```suggestion
        Task<Result<string>> SendMediaAsync(IBotMediaFile mediaFile, string text, SenderInfo sender);
        Task<Result<string>> SendMultipleMediaAsync(List<IBotMediaFile> mediaFiles, string text, SenderInfo sender);
        Task<Result<string>> SendOnlineMediaAsync(IBotOnlineFile file, string text, SenderInfo sender);
```

Бтв не понимаю в чем прикол тащить Result везде подряд, ну он же нахрен тут не нужен и только мешается? Я уже задолбался смотреть на строчки ```if(result.IsFaulted) return;```

2021-05-05 13:05 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendOnlineMedia(IBotOnlineFile file, string text, SenderInfo sender);
@annchous Видала да как умею?

2021-05-05 13:08 UTC, annchous commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendOnlineMedia(IBotOnlineFile file, string text, SenderInfo sender);
> @annchous Видала да как умею?

ага

2021-05-05 16:14 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            if (filename.EndsWith("png") || filename.EndsWith("jpg") ||
Для этого нужно будет этот файл скачать, а это уже как-то не звучит (Filename мы получаем от discord.net)

2021-05-05 16:35 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                botMessage = parseMediaType(message.Attachments.First().Filename) switch
Done

2021-05-05 16:39 UTC, Bibletoon commented on Kysect.BotFramework/Commands/PingCommand.cs
> +            IBotMessage message = new BotSingleMediaMessage("Hi!", new BotOnlinePhotoFile("https://www.ferra.ru/thumb/1800x0/filters:quality(75):no_upscale()/imgs/2020/12/09/06/4390537/dd4dfcc4320bfd
Оно вообще не должно быть тут, закомичено случайно

2021-05-05 16:40 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                filename.EndsWith("wmv") || filename.EndsWith("avi")) return MediaTypeEnum.Video;
Стильно, модно, молодёжно, когда-нибудь потом переделаю

2021-05-05 16:41 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                task.Wait();
Я и так уже во всех списках, где мог быть

2021-05-05 19:44 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendText(string text, SenderInfo sender);
Да перестань ты писать паблики в интерфейсе!

2021-05-06 07:05 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/IBotApiProvider.cs
> +        public Result<string> SendText(string text, SenderInfo sender);
В целом, солидарен с позицией. Паблики в интерфейсах выглядят очень странно т.к. там все всегда паблик.
А вот если ты в интерфейсе решишь сделать что-то не паблик, то просто бан словишь.

2021-05-11 07:34 UTC, FrediKats approved these changes

2021-05-11 07:35 UTC, merged