Fix: check message length
kysect/BotFramework pull request #33
Opened 2021-06-05 18:02 UTC by callbackcat

Processing messages.  Check for non-zero and max length.

2021-06-05 18:41 UTC, Bibletoon commented
Стоит проводить проверку до отправки метода, что бы лишний раз не обращаться к api и не получать лишний exception

2021-06-05 18:43 UTC, annchous commented
Ишую не прикрепил(

2021-06-05 19:19 UTC, FrediKats requested changes

2021-06-05 19:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    message = "The message wasn't sent, the length is too big / small";
1) Лучше разделить на 0 и 2000. Т.к это очень разные проблемы
2) Для too long я бы не писал в лог все строчку. Внезапно, она большая) Можно обрезать и логировать первые 100 символов, например.
3) Если есть возможность - стоит в логах указывать в ответ на что мы сгенерили больше сообщение.

2021-06-06 05:33 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    message = "The message wasn't sent, the length is too big / small";
> я бы не писал в лог все строчку

Так у нас само сообщение в лог не выводится, только сообщение об ошибке

2021-06-06 06:08 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    message = "The message wasn't sent, the length is too big / small";
А, ну значит пункт 4. НАписать что это за строка такая сгенерилась, что сломала все.

2021-06-08 07:37 UTC, Bibletoon approved these changes
Вроде всё хорошо, чувствуется что можно было сделать покрасивее, но это уже оставим до момента рефакторинга всего кода.

2021-06-08 08:10 UTC, FrediKats approved these changes

2021-06-08 08:10 UTC, merged