Small refactor
kysect/BotFramework pull request #34
Opened 2021-06-18 19:33 UTC by Bibletoon

2021-06-19 10:19 UTC, FrediKats requested changes
Уф. Есть конечно тут пару очень своеобразных мест. Можем собраться и провести тех ревью - обсудим код, подумаем что можно переписать. Но уже после того, как это вмерджим.

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    result = SendOnlineMedia(media as IBotOnlineFile, string.Empty, sender);
media is IBotOnlineFile и media as IBotOnlineFile можно смерджить

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +        private Result<string> checkText(string text)
Нейминг

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +            if (mediaFiles.Count > 10)
Вынеси в метод, как и checkText

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                }
Выглядит страшно. А почему мы в одном месте открываем его, а в другом закрываем?

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +
А если с ошибкой свалится в кетче?

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/Core/Commands/BotCommandDescriptor.cs
> +            description, args)
Лучше отключить line wrap, выглядит очень не очень. В таких случаях : base перенести полностью, а не часть аргументов, кажется более привлекательной идеей.

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/Core/Commands/BotCommandDescriptor.cs
> +
В одном месте отступы убрал, а тут нет.

2021-06-19 10:19 UTC, FrediKats commented on Kysect.BotFramework/Core/CommandInvoking/CommandHandler.cs
> +                            $"Command execution failed. Command: {args.CommandName}; arguments: {string.Join(", ", args.Arguments)}")
Имхо, в таких случаях лучше вынести текст ошибки в отдельную переменную, а не делать такие странные врапы.

2021-06-19 15:40 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                    result = SendOnlineMedia(media as IBotOnlineFile, string.Empty, sender);
Я не смог имя придумать нормальное, onlineFile занято (из-за пидорства шарпов, искренне не понимаю почему я не могу реюзнуть)
Если вдохновение придёт - заменю

2021-06-19 15:43 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +        private Result<string> checkText(string text)
Почему-то искренне считал, что приватные поля неймятся camelCasом. Исправлю.

2021-06-19 15:44 UTC, Bibletoon commented
Я только за

2021-06-20 15:51 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +                }
We live in a society
А вообще функция, которая открывает файлы спокойно может находиться в месте своего вызова, но была вытащена для упрощения читаемости кода

2021-06-20 15:52 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +
Поместил закрытие в самое начало catch, так что либо файлы закроются, либо будет ошибка при их закрытии, а такого быть не должно, если пользователь руками не заставил программу сломаться

2021-06-21 05:14 UTC, FrediKats approved these changes

2021-06-21 07:01 UTC, merged