Feat: added dialog context
kysect/BotFramework pull request #40
Opened 2021-08-17 11:25 UTC by Bibletoon

Нападайте. Я уверен, тут прям очень много говна

2021-08-17 11:29 UTC, hrrrrustic commented
@annchous Заходи на тройничок!

2021-08-17 11:55 UTC, hrrrrustic requested changes

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> -                case MediaTypeEnum.Undefined:
Э?

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                                                .GetTextChannel((ulong) sender.ChatId)
Привет тебе от детей налрефа

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordSenderInfo.cs
> +        internal override DialogContext GetDialogContext(BotFrameworkDbContext dbContext)
интернал оверрайд это конечно интересно

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordSenderInfo.cs
> +                dbContext.SaveChanges();
Чета не сходится
Даже не знаю, с чего тут начать

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordSenderInfo.cs
> +        internal override DialogContext GetDialogContext(BotFrameworkDbContext dbContext)
Я если честно не понимаю этот метод
Get что-то, но внутри куча каких-то вставок в базу

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +        private IEnumerable<IAlbumInputMedia> CollectInputMedia(List<IBotMediaFile> mediaFiles, string text,
Поясни

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +        internal override DialogContext GetDialogContext(BotFrameworkDbContext dbContext)
Все тоже самое, что и из прошлого такого метода в другом провайдере

2021-08-17 11:55 UTC, hrrrrustic commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        internal void Update(BotFrameworkDbContext dbContext)
У тебя интернал апдейт, но публичный сеттер у стейта

2021-08-17 13:02 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +        private IEnumerable<IAlbumInputMedia> CollectInputMedia(List<IBotMediaFile> mediaFiles, string text,
Ide сказала можно сделать IEnumerable, я не отказался

2021-08-17 13:02 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordSenderInfo.cs
> +        internal override DialogContext GetDialogContext(BotFrameworkDbContext dbContext)
Забыл переименовать в GetOrCreate

2021-08-17 13:03 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        internal void Update(BotFrameworkDbContext dbContext)
Ну да, в этом и фишка. Update вызывается только после завершения команды, а менять состояние диалога внутри команды пользователь может сколько угодно раз

2021-08-17 13:05 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +        private IEnumerable<IAlbumInputMedia> CollectInputMedia(List<IBotMediaFile> mediaFiles, string text,
Ну такое

2021-08-17 13:05 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> -                case MediaTypeEnum.Undefined:
Ы
Вообще хз почему оно тут было

2021-08-17 13:06 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                                                .GetTextChannel((ulong) sender.ChatId)
Если будет налреф, то привет нужно передавать матерям создателей Discord.net

2021-08-17 13:07 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                                                .GetTextChannel((ulong) sender.ChatId)
Если ты 100500 процентов уверен, что здесь точно бдет DiscordSenderInfo, то почему тогда просто не скастить?

2021-08-17 13:30 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +                                                .GetTextChannel((ulong) sender.ChatId)
Хороший вопрос.

2021-08-17 13:31 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +        private IEnumerable<IAlbumInputMedia> CollectInputMedia(List<IBotMediaFile> mediaFiles, string text,
Ладно, верну

2021-08-20 07:44 UTC, FrediKats requested changes

2021-08-20 07:44 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +            if (contextSenderInfo is null)
Возможно стоит вынести логику работы с базой в Entity.

2021-08-20 07:44 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +                dbContext.SaveChangesAsync();
А зачем тут SaveChanges? Это же должно быть транзакционно. Либо обе сущности добавились и сохранили, либо откатываем всё.

2021-08-20 07:44 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramApiProvider.cs
> +            IEnumerable<IAlbumInputMedia> filesToSend = CollectInputMedia(mediaFiles, text, streams);
Если хочется на интерфейсы переходить, то лучше всё ещё что-то, что представляет собой множество. НАпример, IReadOnlyCollection

2021-08-20 07:44 UTC, FrediKats commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        internal void Update(BotFrameworkDbContext dbContext)
Может тогде SaveChanges?)

2021-08-20 08:20 UTC, hrrrrustic commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +                dbContext.SaveChangesAsync();
Это ты еще Async не заметил!

2021-08-20 09:29 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +                dbContext.SaveChangesAsync();
Асинки убрал.
Так мне же нужно в DialogContext записывать Id SenderInfo, а он появляется только после SaveChanges

2021-08-20 10:17 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            var discordSender = (DiscordSenderInfo)sender;
Потому что BotManager не знает (и не должен знать) с каким сервисом он работает, следовательно он оперирует только SenderInfo

2021-08-20 10:37 UTC, Bibletoon commented on Kysect.BotFramework/ApiProviders/Discord/DiscordApiProvider.cs
> +            var discordSender = (DiscordSenderInfo)sender;
Попробовал сделать дженерики, но там начался ~~DetCheckR~~ сущий ад, так что отказался от этого

2021-08-20 20:41 UTC, FrediKats commented on Kysect.BotFramework/ApiProviders/Telegram/TelegramSenderInfo.cs
> +                dbContext.SaveChangesAsync();
Разве? Блин, я думал оно как-то адекватнее работает, хм.

2021-08-20 20:42 UTC, FrediKats approved these changes

2021-08-21 03:13 UTC, merged