Автодеплой в нюгет на пуш в мастер
kysect/BotFramework pull request #42
Opened 2021-08-21 14:03 UTC by riiji

2021-08-21 14:05 UTC, riiji commented
В secrets.NUGET_SECRET надо засунуть ключ нугета

2021-08-21 14:06 UTC, riiji commented
Но тут еще есть небольшая трабла с версиями, оно берет версию из csproj файла и как бы его там надо менять

2021-08-21 15:06 UTC, FrediKats requested changes
В целом выглядит ок, сможет прокинуть в секреты токен. Только теперь нужно заводить ветку dev и через неё работать. И как-то проверять, что версию обновили в csproj 🤔

2021-08-21 15:06 UTC, FrediKats commented on .github/workflows/main.yml
> +name: CI
Наверное, стоит занеймить более понятно.

2021-08-21 15:19 UTC, riiji commented
> В целом выглядит ок, сможет прокинуть в секреты токен. Только теперь нужно заводить ветку dev и через неё работать. И как-то проверять, что версию обновили в csproj 🤔

Да, на самом деле было 2 варианта

1. Как сейчас, когда надо сделать деплой, то мы пушим в мастер csproj с новой версией. Это не совсем автоматический вариант, но уже лучше чем было

2. Как то вычислять новую версию автоматически, например через timestamp или в secrets сделать какую нибудь переменную

2021-08-21 15:24 UTC, FrediKats commented
Вариант с апом версий в целом ок. Я бы на нём остановился. Будет хорошо, если мы будет поддерживать нормальную очевидную версионность.

2021-08-22 09:01 UTC, riiji commented
Ага, смотри, я надеюсь что оно работает, через github secrets я сделал хранилище версии для бота
От тебя нужно:

1. поставить secrets.GH_SECRETS=[персональный апи токен], токен должен быть минимум с правами repo
2. поставить secrets.BOT_VERSION=0.1.2, чтобы он его изменял
3. поставить secrets.NUGET_SECRET=[токен нюгета], ну это я писал выше

2021-08-22 10:35 UTC, merged