Feat: change command descriptor to attribute
kysect/BotFramework pull request #45
Opened 2021-10-13 19:39 UTC by Bibletoon

Мне что-то ударило в голову, я решил переделать дескриптор в атрибут. Почти уверен, что это не нужно мёрджить в мастер пока что, просто хочу послушать мнение про эту грязь

2021-10-14 11:34 UTC, FrediKats commented
Ни на что не намекаю, но в шарп завезли статик методы интерфейсам.

2021-10-30 18:34 UTC, FrediKats commented
bump @Bibletoon

2021-11-05 06:11 UTC, s4xack commented
![Screenshot_20211105-091056.jpg](https://user-images.githubusercontent.com/35222382/140466365-17a8f7ea-201a-4f05-ac69-fd0da30faedb.jpg)
@Bibletoon

2021-11-05 07:40 UTC, Bibletoon commented
Ладно, ща доделаю...

2021-11-05 07:48 UTC, FrediKats commented
@Bibletoon только тоже на dev поменяй бейз бранч.

2021-11-05 14:09 UTC, Bibletoon commented
> Ни на что не намекаю, но в шарп завезли статик методы интерфейсам.

Кста так и не понял, на что ты намекал

2021-11-05 14:16 UTC, FrediKats reviewed
На рефлекшене немного умер.

2021-11-05 14:16 UTC, FrediKats commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                throw new BotValidException("Command must have descriptor attribute");
А почему сразу не сохранять мапинг? Зачем потом повторно резолвить?

2021-11-05 14:16 UTC, FrediKats commented on Kysect.BotFramework/Core/Commands/IBotCommand.cs
> +            => GetType().GetBotCommandDescriptorAttribute();
Не нравится мне рефлексия в интерфесе прям (

2021-11-05 14:16 UTC, FrediKats commented on Kysect.BotFramework/Core/Tools/Extensions/ServiceProviderExtensions.cs
> +            var descriptorLookup = callSiteFactory.GetFieldValue("_descriptorLookup");
Каво... что тут проихсодит?

2021-11-05 14:16 UTC, FrediKats commented on Kysect.BotFramework/Core/Tools/Extensions/ServiceProviderExtensions.cs
> +            if (descriptorLookup is IDictionary dictionary)
Инвертировать?

2021-11-05 14:17 UTC, FrediKats commented
Может @ronimizy хочет посмотреть?

2021-11-05 14:18 UTC, ronimizy commented
> Может @ronimizy хочет посмотреть?

Сегодня после рубежки по физике гляну

2021-11-05 14:32 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                throw new BotValidException("Command must have descriptor attribute");
Не очень понял маппинг кого с кем

2021-11-05 14:32 UTC, Bibletoon commented on Kysect.BotFramework/Core/Tools/Extensions/ServiceProviderExtensions.cs
> +            var descriptorLookup = callSiteFactory.GetFieldValue("_descriptorLookup");
Доступ к приватным полям 😁

2021-11-05 15:18 UTC, ronimizy requested changes

2021-11-05 15:18 UTC, ronimizy commented on Kysect.BotFramework/Core/Tools/Extensions/GetAttributeExtensions.cs
> +                    as BotCommandDescriptorAttribute);
```suggestion
            => Attributes.GetOrAdd(
                type,
                t => t.GetCustomAttribute<BotCommandDescriptorAttribute>();
```

2021-11-05 15:18 UTC, ronimizy commented on Kysect.BotFramework/Core/CommandInvoking/CommandHandler.cs
> +                    $"Command [{descriptor.CommandName}] cannot be executed: {canExecute}");
descriptor null check?

2021-11-05 15:18 UTC, ronimizy commented on Kysect.BotFramework/Core/Commands/BotCommandDescriptor.cs
>          }
params?

2021-11-05 15:18 UTC, ronimizy commented on Kysect.BotFramework/Core/Commands/IBotCommand.cs
> +            => GetType().GetBotCommandDescriptorAttribute();
лучше в классе с экстеншеном сделай дженерик метод where T : IBotCommand, и вызывай существующий метод от typof(T)

2021-11-05 15:18 UTC, ronimizy commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
кэшировать бы все получаемые рефлекшенами геттеры и сеттеры

2021-11-05 19:31 UTC, Bibletoon commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
Думаю, пока можно просто кешировать типы команд по их имени, а если потом ещё будем использовать рефлекшены подумать о кешировании всего

2021-11-05 19:41 UTC, ronimizy commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
Не знаком со структурой кода. В команде есть свойство с её именем или ты хочешь юзать nameof(T)? (Второй вариант с подвохом)

2021-11-05 19:43 UTC, Bibletoon commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
Есть, это то, как пользователь её вызывает
Типа !*ping*

2021-11-05 19:59 UTC, ronimizy commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
А, ну тогды ок, я бы вообще с помощью Assembly Scanning на этапе конфигурации все добавлял (ну или хотя бы дал возможность пользователю это сделать, как например в Discord.NET реализовано добавление модулей)

2021-11-05 21:24 UTC, Bibletoon commented on Kysect.BotFramework/Core/Tools/Helpers/ReflectionHelpers.cs
> +        public static object GetFieldValue(this object obj, string fieldName)
Пока просто прощупываю почву, в планах есть assembly scanning

2021-11-07 16:09 UTC, FrediKats approved these changes

2021-11-07 17:22 UTC, merged