Feat: optional context
kysect/BotFramework pull request #64
Opened 2022-06-08 08:47 UTC by Mihinator3000

#52

2022-06-09 03:46 UTC, FrediKats requested changes
А мне не хотим просто in memory заюзать на случай, если не инициализировано вообще? Или в полном отказе есть какой-то профит помимо "оно не будет падать, если не указать"?

Ну и оставил коммент на рефак.

2022-06-09 03:46 UTC, FrediKats commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        }
1) Мы не определяем _senderInfoId, но... Какой смысл этого поля. Там разве не всегда лежит senderInfo.UserSenderId? Может вообще выпилить поле?
2) State не инициализируется и остаётся =0. Думаю, стоит всё же пойти в сторону более очевидно int? State = null;

2022-06-09 03:46 UTC, FrediKats commented on Kysect.BotFramework/Core/BotManager.cs
> +            }
Мне не очень нравится концептуально логика, которая построенная на null проверках.

Конкретно в этом кейсе я бы предложил сделать обёртку, например 
`interface IDialogContextPrivider : IDisposable` и две реализации - PersistentStorageDialogContextPrivider и NullDialogContextPrivider. Но можно в целом отказаться от этого.

2022-06-09 06:54 UTC, Bibletoon commented
Оставил пару мыслей в дискорде, в текущем виде реализацию оставлять не хотелось бы, потом читать все эти if'ы крайне неприятно т.к. не помнишь уже зачем они тут

2022-06-10 10:36 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        }
В _senderInfoId лежит database pk для SenderInfo, так что пришлось оставить

2022-06-10 20:29 UTC, Bibletoon requested changes
Уже лучше, но можно ещё лучше!

2022-06-10 20:29 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                new StorageDialogContextProvider(p.GetRequiredService<BotFrameworkDbContext>()));
То, что ты суёшь Scoped сервис (DbContext) внутрь Singleton сервиса, заставляет задуматься о том всё ли идёт хорошо

2022-06-10 20:29 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
Когда я писал предложение по вынесению контекста в сервис, имел в виду что пользователю самому нужно будет инжектить IDIalogContextProvider внутрь команд, которые этот контекст используют

2022-06-10 20:29 UTC, Bibletoon commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +        public DialogContext DialogContext => _serviceProvider
В сообщении писал, что хотелось бы избавиться от контекста в CommandContainer

2022-06-10 20:29 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/Providers/StorageDialogContextProvider.cs
> +    public SenderInfo SenderInfo
Синглтон сервис у которого состояние меняется через сеттер не выглядит надёжно и практично

2022-06-10 20:29 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        public int? State { get; set; }
Можно вот тут внутри сеттера вызывать SaveChanges, чтобы не пришлось в IDIalogContextProvider делать метод для сохранения

2022-06-10 21:14 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        public int? State { get; set; }
Сейв без async получается?

2022-06-11 11:28 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +        public int? State { get; set; }
Ну получается что так

2022-06-14 21:28 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
А как подразумевается этот инжект напрямую в команду? Пока что я смог придумать это только через новый интерфейс типа IBotContextCommand, добавляющий IDialogContextProvider в методы, но это решение выглядит странновато

2022-06-17 19:02 UTC, Mihinator3000 reviewed
Я тут отметил пару моментов которые мне до сих пор кажутся странными, но я не знаю что с ними делать и надо ли вообще что-то менять

2022-06-17 19:02 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
Без получения диалог контекста у нас не идет сохранение в базу данных, хотя по сути он здесь и не нужен

2022-06-17 19:02 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Contexts/Providers/SenderInfoProvider.cs
> +}
0 идей как избавиться от DI сервиса, имеющего сэттер с SenderInfo, хотя бы он теперь новый для каждого сообщения

2022-06-18 04:03 UTC, FrediKats commented on Kysect.BotFramework/Core/BotManager.cs
> +            var commandHandler = new CommandHandler(scope.ServiceProvider);
А в ASP же вроде также 🤔

2022-06-18 06:17 UTC, Bibletoon requested changes

2022-06-18 06:17 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/Providers/IDialogContextProvider.cs
> +    DialogContext GetDialogContext();
Как мне кажется можно SenderInfo принимать как параметр в GetDialogContext, тогда от сервиса с SenderInfo можно избавиться

2022-06-18 06:17 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                ServiceCollection.AddScoped<IDialogContextProvider, NullDialogContextProvider>();
Если при создании бота пользователь сознательно не включил базу данных, то ему контекст диалога как мне кажется не нужен. Если захочет его использовать: добавит параметр в конструктор, получит исключение и пойдёт включать базу, чтобы было где диалог хранить

2022-06-18 06:17 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/SenderInfo.cs
> +        public abstract ContextType ContextType { get; }
Может стоит это поле сделать protected, как мне кажется одна из идей BF в том, чтобы абстрагироваться от платформы, на которой работает бот, а тут этот указатель наружу торчит

2022-06-18 06:17 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/Providers/IDialogContextProvider.cs
> +    DialogContext GetDialogContext();
А сам SenderInfo передавать в CommandContainer'е, как раньше (до добавления контекста)

2022-06-18 06:56 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManager.cs
> +            var commandHandler = new CommandHandler(scope.ServiceProvider);
Что именно? Если это про новый скоуп на новый реквест, то да, я это оттуда взял

2022-06-18 06:58 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Contexts/DialogContext.cs
> +            => SenderInfo = senderInfo;
Это для создания контекста когда нет db

2022-06-18 07:05 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                ServiceCollection.AddScoped<IDialogContextProvider, NullDialogContextProvider>();
В чем тогда идея? В NullDialogContextProvider’е вместо контекста с текущим сэндером возвращать null или кидать эксепшен?

2022-06-18 07:46 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                ServiceCollection.AddScoped<IDialogContextProvider, NullDialogContextProvider>();
Удалить NullDialogContextProvider
Если нужен контекст - регистрируй базу, тогда нужный сервис можно будет получить
Если нет - то в коллекции просто не будет реализации IDialogContextProvider т.к. он не нужен

2022-06-18 08:05 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                ServiceCollection.AddScoped<IDialogContextProvider, NullDialogContextProvider>();
Тут мне кажется проблема в том, что при обработке сообщения мы всегда должны получать контекст, в противном случае не будет идти запись в бд, а если удалить nullcontextprovider, ошибка будет уже там вылетать. И еще может лучше более осмысленную ошибку кидать, а не полагаться не дефолтный эксепшен?

2022-06-18 08:12 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
Попробовал удалить эти две строчки - всё работает так же, как и с ними. Может я что-то недопонял?

2022-06-18 08:13 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManagerBuilder.cs
> +                ServiceCollection.AddScoped<IDialogContextProvider, NullDialogContextProvider>();
> при обработке сообщения мы всегда должны получать контекст

Не совсем понял зачем, как написал в сообщении выше без получения его всё работает так же

2022-06-18 08:23 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
У нас при вызове команды, которая не обращается к контексту, не будет сохранения никаких данных в бд, если же обращаться с другого места в команде, то все ок, возможно так и планировалось

2022-06-18 08:30 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
Ну так базу нужно изменять только когда мы меняем стейт у диалога, а для того, чтобы его поменять нам необходимо достать провайдер внутри команды

2022-06-18 08:36 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/BotManager.cs
> +            DialogContext dialogContext = dialogContextProvider.GetDialogContext();
То есть нам не нужна никакая инфа о пользователе если у него стейт дефолт? Окей

2022-06-18 12:26 UTC, Bibletoon commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +            ?? throw new BotValidException("Database context options were not initialized");
Я вроде когда-то (в около-первом ревью) писал, что хотелось бы избавиться он контекста в CommandContainer'e. Мне кажется что IDialogContextProvider должен внедряться самим пользователем прямо внутрь команды

Возможно хочется послушать альтернативное мнение @FrediKats

2022-06-18 12:37 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +            ?? throw new BotValidException("Database context options were not initialized");
Я видимо неправильно понял что Фреди писал. Но сейчас пользователю чтобы получить контекст надо будет догадаться заколлить провайдер и передать туда senderinfo из контейнера? Мне кажется это слегка запутанным будет

2022-06-18 12:44 UTC, Bibletoon commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +            ?? throw new BotValidException("Database context options were not initialized");
> догадаться заколлить провайдер

Напрямую колить провайдер ему ненужно, просто в конструкторе добавить параметр IDialogContextProvider
Про то, что догадаться самому нельзя, согласен, надо завести таску на документацию.

Вообще идея такого подхода в том, что можно будет накидывать разные модули, а пользователь сам будет брать нужные через DI

2022-06-18 12:49 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +            ?? throw new BotValidException("Database context options were not initialized");
Не уверен, что это наилучшее решение, но я вижу его плюсы, щас поправлю

2022-06-19 07:12 UTC, Bibletoon commented on Kysect.BotFramework/Core/Commands/CommandContainer.cs
> +            ?? throw new BotValidException("Database context options were not initialized");
> Еще мы теряем нормальное сообщение для эксепшена

Ну, можно в теории вернуть NullDialogProvider и просто в конструкторе у него кидать эксепшн, но это решение лучше оставить на случай "Прям очень надо будет"

2022-06-19 07:28 UTC, Bibletoon approved these changes

2022-06-19 07:28 UTC, Bibletoon commented on Kysect.BotFramework/Core/BotNewMessageEventArgs.cs
> +public class BotNewMessageEventArgs
Мб оставить название "BotEventArgs", чисто субъективное предложение

2022-06-19 07:46 UTC, Mihinator3000 commented
Все пофиксил, осталось чтобы @FrediKats глянул

2022-06-19 07:52 UTC, FrediKats approved these changes
В целом ок.
Я предлагаю зафиксировать все мысли и обсуждения этого PR в отдельную ишую, но не пытаться сейчас решать проблемы о которых мы не знаем. Вмёрджить это, собрать нюгет и попробовать его применить. Использовав в реальном проекте станет более понятно насколько хороши были те или иные решения.

2022-06-19 17:59 UTC, FrediKats commented
@Bibletoon так что, ок? Смёрджишь?

2022-06-20 17:04 UTC, merged