Feat: analyzer
kysect/BotFramework pull request #75
Opened 2022-07-16 11:17 UTC by Mihinator3000

2022-07-17 15:09 UTC, FrediKats requested changes

2022-07-17 15:09 UTC, FrediKats commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
Я бы условие в отдельный метод вынес, как минимум. Там же ещё может быть String.Empty?)

2022-07-17 15:09 UTC, FrediKats commented on Kysect.BotFramework.Internal/Kysect.BotFramework.Internal.csproj
> +	<AssemblyName>Kysect.BotFramework.Internal</AssemblyName>
А почему Internal? Это же что-то, что должно ставиться пользователем себе, а не мы у себя используем. Если это анализаторы, то может пусть и будет что-то тип анализаторов?

2022-07-17 15:09 UTC, FrediKats commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
Мне кажется, что тут что-то не так. Я ожидал бы, что ссылки будут на основную либу, а не из неё. Получается, что человек может поставить отдельно анализаторы. И что если пользователь хочет использовать только либу без анализаторов, то он не сможет. Да и с точки зрения архитекуры - есть кор либа, а есть тулы для неё.

2022-07-17 15:32 UTC, Mihinator3000 commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
Я над нормальной логикой хотел позже поработать, когда уже анализатор будет запушен, чтобы точно знать, что он дальше будет развиваться, но приму к сведению.

2022-07-17 15:32 UTC, Mihinator3000 commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
А, и еще у нас string.Empty не константа, ее нельзя в аттрибуты передавать

2022-07-17 15:34 UTC, FrediKats commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
Валидно, да. Тогда я не прав.

2022-07-17 15:39 UTC, Mihinator3000 commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
Я если честно думал, что анализатор (в лучшем случае) должен быть обязательным, чтобы проект не компилился пока не будет все пофикшено (речь идет скорее про опциональные аргументы), то есть это не дополнение, а одна из частей либы. Отсюда в принципе и название internal. 
Возможно конечно так не делается в нормальной практике.
Хотелось бы еще, чтобы @Bibletoon сказал, как он себе это представлял

2022-07-17 15:42 UTC, FrediKats commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
Ну да, если что, я просто мимопроходил и накинул. У вас с Библетуном ясно больше понимания в происходящем.

2022-07-18 12:53 UTC, Bibletoon commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
Я согласен что делать анализатор где-то сбоку и необязательным - идея не очень, так как он как раз нужен для адекватной работы с библиотекой и мало кто сам будет их подключать. Но и текущий нейминг выглядит как-то не очень кмк. Из идей у меня есть только такое: сделать проект Abstractions, где будут абстракции нужные для работы с библиотекой (интерфейс команды, атрибуты, интерфейсы сервисов), сделать отдельный проект с анализаторами и проект с кор логикой, который будет на два предыдущих ссылаться.

2022-07-18 20:13 UTC, Bibletoon commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +                a.Name.ToString().Contains("BotCommandDescriptor"));
Лучше сделать nameof(BotCommandDescriptor) чем вхардкоженную строку

2022-07-18 20:13 UTC, Bibletoon commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
А если у нас аргумент null, разве проверка через вызов ToString не упадёт?

2022-07-18 20:13 UTC, Bibletoon commented on Kysect.BotFramework.Internal/Kysect.BotFramework.Internal.csproj
> +  </ItemGroup>
Это убрать можно

2022-07-18 20:49 UTC, Mihinator3000 commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +                a.Name.ToString().Contains("BotCommandDescriptor"));
Тут проблема в том, что нет класса BotCommandDescriptor, есть BotCommandDescriptorAttribute, логику в принципе переписать надо

2022-07-18 20:51 UTC, Mihinator3000 commented on Kysect.BotFramework.Internal/Analyzers/EmptyCommandNameAnalyzer.cs
> +        if (commandDescriptor.ArgumentList?.Arguments[0].ToString() is "null" or "\"\"")
Ну null это тоже аргумент, показатель что что-то передано, не упадет

2022-07-18 20:52 UTC, Mihinator3000 commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
Получается 3 нюгета по итогу будет?

2022-07-20 09:56 UTC, Mihinator3000 commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
У нас в проекте очень сильная связь между классами, особенно с SenderInfo и его internal свойствами и методами, я не уверен, что это можно нормально выделить в Abstractions

2022-07-20 12:00 UTC, Mihinator3000 commented on Kysect.BotFramework/Core/Contexts/Providers/StorageDialogContextProvider.cs
> +        => (senderInfo as SenderInfo).GetOrCreateDialogContext(_dbContext);
Связанность убрать особо не удалось, теперь есть вот такой костыль, 0 идей как его починить нормально

2022-08-29 08:33 UTC, Bibletoon commented on Kysect.BotFramework/Core/Contexts/Providers/StorageDialogContextProvider.cs
> +        => (senderInfo as SenderInfo).GetOrCreateDialogContext(_dbContext);
Надо это переделать на визиторы, чтобы убрать отвратительные internal методы и гибко добавлять новые контексты, ишую заведу, позже сделаю

2022-08-29 08:35 UTC, Bibletoon commented on Kysect.BotFramework/Kysect.BotFramework.csproj
> +    <ProjectReference Include="..\Kysect.BotFramework.Internal\Kysect.BotFramework.Internal.csproj" />
> Получается 3 нюгета по итогу будет?

Ну если получится кор логику с анализаторами объединить, то можно два, но как-то не знаю стоит ли сжимать количество нюгетов

2022-08-29 08:40 UTC, Bibletoon approved these changes
Ну в целом то ок, отделение абстракций явно показала кривые моменты архитектуры, надо будет фиксить

2022-08-29 12:27 UTC, Mihinator3000 commented
Не могу замержить с changes requested, еще и sonar не залогинился

2022-08-30 17:31 UTC, FrediKats approved these changes

2022-08-30 17:33 UTC, merged